services:
  - type: web
    name: foodmesh-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MongoDbSettings__ConnectionString
        sync: false
      - key: MongoDbSettings__DatabaseName
        value: FoodMeshDb
