<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Domain\FoodMesh.Domain.csproj" />
    <ProjectReference Include="..\Shared\FoodMesh.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BusinessApiService\**" />
    <EmbeddedResource Remove="BusinessApiService\**" />
    <None Remove="BusinessApiService\**" />
  </ItemGroup>

</Project>
